# Form implementation generated from reading ui file 'ui/dialog_add.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_add(object):
    def setupUi(self, dialog_add):
        dialog_add.setObjectName("dialog_add")
        dialog_add.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_add.resize(300, 340)
        dialog_add.setMinimumSize(QtCore.QSize(300, 340))
        dialog_add.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog_add)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=dialog_add)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_last_name = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_last_name.setText("")
        self.input_last_name.setObjectName("input_last_name")
        self.verticalLayout.addWidget(self.input_last_name)
        self.input_first_name = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_first_name.setText("")
        self.input_first_name.setObjectName("input_first_name")
        self.verticalLayout.addWidget(self.input_first_name)
        self.input_patronymic = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_patronymic.setText("")
        self.input_patronymic.setObjectName("input_patronymic")
        self.verticalLayout.addWidget(self.input_patronymic)
        self.input_date = QtWidgets.QDateEdit(parent=dialog_add)
        self.input_date.setMaximumSize(QtCore.QSize(15000, 16777215))
        self.input_date.setCalendarPopup(True)
        self.input_date.setObjectName("input_date")
        self.verticalLayout.addWidget(self.input_date)
        self.input_team = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_team.setMaximumSize(QtCore.QSize(16777168, 16777215))
        self.input_team.setText("")
        self.input_team.setObjectName("input_team")
        self.verticalLayout.addWidget(self.input_team)
        self.input_city = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_city.setText("")
        self.input_city.setObjectName("input_city")
        self.verticalLayout.addWidget(self.input_city)
        self.input_squad = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_squad.setText("")
        self.input_squad.setObjectName("input_squad")
        self.verticalLayout.addWidget(self.input_squad)
        self.input_position = QtWidgets.QLineEdit(parent=dialog_add)
        self.input_position.setText("")
        self.input_position.setObjectName("input_position")
        self.verticalLayout.addWidget(self.input_position)
        self.button_save = QtWidgets.QPushButton(parent=dialog_add)
        self.button_save.setObjectName("button_save")
        self.verticalLayout.addWidget(self.button_save)
        self.button_cancel = QtWidgets.QPushButton(parent=dialog_add)
        self.button_cancel.setObjectName("button_cancel")
        self.verticalLayout.addWidget(self.button_cancel)

        self.retranslateUi(dialog_add)
        QtCore.QMetaObject.connectSlotsByName(dialog_add)

    def retranslateUi(self, dialog_add):
        _translate = QtCore.QCoreApplication.translate
        dialog_add.setWindowTitle(_translate("dialog_add", "Dialog"))
        self.label.setText(_translate("dialog_add", "Добавление игрока"))
        self.input_last_name.setPlaceholderText(_translate("dialog_add", "Фамилия"))
        self.input_first_name.setPlaceholderText(_translate("dialog_add", "Имя"))
        self.input_patronymic.setPlaceholderText(_translate("dialog_add", "Отчество"))
        self.input_team.setPlaceholderText(_translate("dialog_add", "Команда"))
        self.input_city.setPlaceholderText(_translate("dialog_add", "Город"))
        self.input_squad.setPlaceholderText(_translate("dialog_add", "Состав"))
        self.input_position.setPlaceholderText(_translate("dialog_add", "Позиция"))
        self.button_save.setText(_translate("dialog_add", "Сохранить"))
        self.button_cancel.setText(_translate("dialog_add", "Отмена"))
