# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Players(object):
    def setupUi(self, Players):
        Players.setObjectName("Players")
        Players.resize(977, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Players)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_container = QtWidgets.QWidget(parent=self.centralwidget)
        self.button_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_container.setObjectName("button_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(parent=self.button_container)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_search = QtWidgets.QPushButton(parent=self.button_container)
        self.button_search.setObjectName("button_search")
        self.horizontalLayout.addWidget(self.button_search)
        self.button_remove = QtWidgets.QPushButton(parent=self.button_container)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout.addWidget(self.button_remove)
        self.button_save_to_xml = QtWidgets.QPushButton(parent=self.button_container)
        self.button_save_to_xml.setObjectName("button_save_to_xml")
        self.horizontalLayout.addWidget(self.button_save_to_xml)
        self.button_load_from_xml = QtWidgets.QPushButton(parent=self.button_container)
        self.button_load_from_xml.setObjectName("button_load_from_xml")
        self.horizontalLayout.addWidget(self.button_load_from_xml)
        self.button_tree_view = QtWidgets.QPushButton(parent=self.button_container)
        self.button_tree_view.setObjectName("button_tree_view")
        self.horizontalLayout.addWidget(self.button_tree_view)
        self.verticalLayout.addWidget(self.button_container)
        self.stacked_widget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table = QtWidgets.QTableWidget(parent=self.page)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout_3.addWidget(self.table)
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tree = QtWidgets.QTreeWidget(parent=self.page_2)
        self.tree.setObjectName("tree")
        self.verticalLayout_2.addWidget(self.tree)
        self.stacked_widget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stacked_widget)
        Players.setCentralWidget(self.centralwidget)

        self.retranslateUi(Players)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Players)

    def retranslateUi(self, Players):
        _translate = QtCore.QCoreApplication.translate
        Players.setWindowTitle(_translate("Players", "MainWindow"))
        self.button_add.setText(_translate("Players", "Добавить"))
        self.button_search.setText(_translate("Players", "Поиск"))
        self.button_remove.setText(_translate("Players", "Удалить"))
        self.button_save_to_xml.setText(_translate("Players", "Сохранить в XML"))
        self.button_load_from_xml.setText(_translate("Players", "Загрузить из XML"))
        self.button_tree_view.setText(_translate("Players", "Показать дерево"))
        self.tree.headerItem().setText(0, _translate("Players", "Игроки"))
