# Form implementation generated from reading ui file 'ui/paginator.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Paginator(object):
    def setupUi(self, Paginator):
        Paginator.setObjectName("Paginator")
        Paginator.resize(597, 50)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Paginator)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_first = QtWidgets.QPushButton(parent=Paginator)
        self.button_first.setObjectName("button_first")
        self.horizontalLayout.addWidget(self.button_first)
        self.button_previous = QtWidgets.QPushButton(parent=Paginator)
        self.button_previous.setObjectName("button_previous")
        self.horizontalLayout.addWidget(self.button_previous)
        self.label_page_info = QtWidgets.QLabel(parent=Paginator)
        self.label_page_info.setObjectName("label_page_info")
        self.horizontalLayout.addWidget(self.label_page_info)
        self.button_next = QtWidgets.QPushButton(parent=Paginator)
        self.button_next.setObjectName("button_next")
        self.horizontalLayout.addWidget(self.button_next)
        self.button_last = QtWidgets.QPushButton(parent=Paginator)
        self.button_last.setObjectName("button_last")
        self.horizontalLayout.addWidget(self.button_last)
        self.combo_per_page = QtWidgets.QComboBox(parent=Paginator)
        self.combo_per_page.setObjectName("combo_per_page")
        self.horizontalLayout.addWidget(self.combo_per_page)

        self.retranslateUi(Paginator)
        QtCore.QMetaObject.connectSlotsByName(Paginator)

    def retranslateUi(self, Paginator):
        _translate = QtCore.QCoreApplication.translate
        Paginator.setWindowTitle(_translate("Paginator", "Form"))
        self.button_first.setText(_translate("Paginator", "<<"))
        self.button_previous.setText(_translate("Paginator", "<"))
        self.label_page_info.setText(_translate("Paginator", "Страница 1 из 1"))
        self.button_next.setText(_translate("Paginator", ">"))
        self.button_last.setText(_translate("Paginator", ">>"))
