from typing import Protocol
from services.timetable import Timetable
from domain.passenger.passenger import Passenger


class TimetableRepository(Protocol):
    def load(self) -> Timetable: ...
    def save(self, timetable: Timetable) -> None: ...


class PassengerRepository(Protocol):
    def get(self, passenger_id: int, timetable: Timetable) -> Passenger: ...
    def save(self, passenger: Passenger) -> None: ...
    def remove_tickets_for_compound(self, compound_id: int) -> None: ...
    def next_id(self) -> int: ...

class SimulationClock(Protocol):
    def now(self) -> int: ...
    def advance(self, minutes: int) -> int: ...
    def set_to(self, target_minutes: int) -> int: ...
    def reset(self) -> None: ...
